export { ReactComponent as DeleteIcon } from './icon-delete.svg'
export { ReactComponent as EditIcon } from './icon-edit.svg'
export { ReactComponent as MinusIcon } from './icon-minus.svg'
export { ReactComponent as PlusIcon } from './icon-plus.svg'
export { ReactComponent as ReplyIcon } from './icon-reply.svg'
